### ISSUE TITLE
Extend build system to target a Web Extension

### ISSUE THREAD

**Issue by infojunkie** [meedan/check-mark#2]
The default build script for React targets a web app. In our case, we want to target a browser plugin, so there should be additional build steps to generate the correct Web Extension structure. 

@caiosba, plz add links to relevant parts of the `bridge-client` source that performs these steps.

**Comment by caiosba** [comment]
The `gulpfile` that contains the tasks to compile the code as an extension: https://github.com/meedan/bridge-client/blob/master/gulpfile.babel.js

The `npm` script that zips the generated code: https://github.com/meedan/bridge-client/blob/master/package.json#L11

The related `webpack` configuration: https://github.com/meedan/bridge-client/blob/master/webpack/config.js

Chrome extension requires a special file structure... this is handled by this directory: https://github.com/meedan/bridge-client/tree/master/src/browser. The files here are responsible for wrapping the actual web app code (which in `bridge-client` case is stored at https://github.com/meedan/bridge-client/tree/master/src/app).
