### ISSUE TITLE
Allow a user to invoke the extension via a button

### ISSUE THREAD

**Issue by infojunkie** [meedan/check-mark#3]
The extension should install a button in the browser toolbar. Clicking this button opens the app dialog.

@caiosba: plz link to relevant code in `bridge-client`.

**Comment by caiosba** [comment]
This is done by declaring a `browser_action` in the `manifest.json` file: https://github.com/meedan/bridge-client/blob/master/src/browser/extension/manifest.json.example#L6-L10.
