### ISSUE TITLE
Login via Check API

### ISSUE THREAD

**Issue by infojunkie** [meedan/check-mark#4]
Before allowing the user to submit URLs to Check via the extension, they need to login to Check. Display a login dialog that communicates with the Check API to obtain a connection token.

@caiosba plz link to relevant code in `bridge-client`.

**Comment by caiosba** [comment]
We currently support login using Twitter and Facebook (OmniAuth). Both login methods call this `requestAuth` method here: https://github.com/meedan/bridge-client/blob/e488015bfd13823a835d1b3f66a2b4e2a565959c/src/app/actions/bridge.js#L58-L80

**Comment by JamesZXie** [comment]
My understanding of how loginTwitter and loginFacebook (below the highlighted portion) work are they will continue to call requestAuth until the Facebook/Twitter server gets back to them, and then they will dispatch a command to the store go to the next page, "menu". Is this correct?

**Comment by JamesZXie** [comment]
Other than the three functions I mentioned (requestAuth, loginTwitter, loginFacebook) and the dependencies they rely on to run, do I need to take anything else from the github linked above for the login process only? I've put in the first function just in case (request), but it seems like the rest deal with other processes as the extension runs.

**Comment by JamesZXie** [comment]
In bridge-client/src/app/store/configureStore.js, I can't find "rootReducer", which it imports from .../reducers. Is it included in the redux dependency or am I looking in the wrong folders?

**Comment by caiosba** [comment]
The login methods ask the backend whether the user is logged in... if he is already logged in, then he is redirected to the menu. If he is not, the backend will redirect the user to the third-party website (Twitter or Facebook) and then close the window. The client side notices that the window was closed and re-checks with the backend if the authentication was successful.

The login* functions and requestAuth should be enough, yes :)

The "rootReducer" is just the "imported" name... what is being imported is actually this: https://github.com/meedan/bridge-client/blob/master/src/app/reducers/index.js#L5.
