### ISSUE TITLE
Show URL submission dialog

### ISSUE THREAD

**Issue by infojunkie** [meedan/check-mark#5]
After user login, the extension should show a dialog that allows the user to submit the current URL to Check. The dialog should show the user's projects on Check, which are all the projects where the user is active. Coordinate with the Meedan dev team to access this API endpoint.

The user can also enter a comment that will be displayed along with the submitted URL. When "Submit" is clicked, the extension calls another API endpoint to perform the actual URL submission. Check API will return a link to the submission on Check: this URL should be displayed as a result message.

@caiosba plz link to relevant code from `bridge-client`

**Comment by caiosba** [comment]
This is where we get the user's projects from: https://github.com/meedan/bridge-client/blob/e488015bfd13823a835d1b3f66a2b4e2a565959c/src/app/actions/bridge.js#L124.

This is where the media is submitted to Check: https://github.com/meedan/bridge-client/blob/e488015bfd13823a835d1b3f66a2b4e2a565959c/src/app/actions/bridge.js#L202-L211

**Comment by JamesZXie** [comment]
My understanding of how loginTwitter and loginFacebook (below the highlighted portion) work are they will continue to call requestAuth until the Facebook/Twitter server gets back to them, and then they will dispatch a command to the store go to the next page, "menu". Is this correct?

**Comment by mazhang2718** [comment]
We're currently running into this error when submitting the current active URL:
<img width="523" alt="screen shot 2017-02-18 at 2 24 31 pm" src="https://cloud.githubusercontent.com/assets/12781097/23097549/3e63e81a-f5eb-11e6-96c2-9d30d9a5c6c9.png">

I'm assuming that this is because the data submitted to the Check API is of a different format than the data submitted to the Bridge API - is there a way to account for this? I think that one of the methods in the Check [relay.json](https://github.com/meedan/check-web/blob/develop/data/relay.json) file needs to be called, but I'm not completely sure which one to use.

**Comment by mazhang2718** [comment]
@infojunkie / @caiosba:

We've successfully been able to submit the current open page to the Check API through the extension - however, I'm not quite sure that the data that we're sending is exactly correct. From the [check web client](https://github.com/meedan/check-web/blob/0ced8591be482830bef4a132f080f3bc39a5c687/src/app/components/media/CreateMedia.js), it seems like we just need to submit a url, quote, image, and project ID through Relay. AKA:

` 
Relay.Store.commitUpdate(
      new CreateProjectMediaMutation({
        url,
        quote,
        image,
        project: context.project,
      }),
      { onSuccess, onFailure },
    );
`
When we leave the quote as an empty string, we get a 'Validation failed: Media can't be blank' error; and when we use the url as a quote, the submission looks a bit different than the web version (pic below). Is there something else we need to get the submission to match the web format?

<img width="813" alt="submission" src="https://cloud.githubusercontent.com/assets/12781097/23439069/c660321a-fdc9-11e6-86a3-6e079f55f527.png">

Another question I had was regarding the submission preview - it looks like Embed.ly is being used to generate previews, but for websites other than Twitter/Facebook, the preview either doesn't look as nice or doesn't load at all. Should we keep the preview, or maybe just show the URL being submitted? 

<img width="501" alt="preview" src="https://cloud.githubusercontent.com/assets/12781097/23439141/3885b86a-fdca-11e6-9067-a97738266eff.png">

Thanks!

**Comment by mazhang2718** [comment]
I was able to invoke a callback after submitting the media, but I'm having trouble submitting the comment afterwards. I'm not entirely sure what the fields of the following code block are supposed to contain - could you provide an example for each field? Thanks!

`
    Relay.Store.commitUpdate(

      new CreateCommentMutation({

        parent_type: annotated_type.replace(/([a-z])([A-Z])/, '$1_$2').toLowerCase(),

        annotator,
        annotated,
        image,
        context: that.getContext(),
        annotation: {
          text: comment,
          annotated_type,
          annotated_id,
        },
      }),
      { onSuccess, onFailure },
    );
`

**Comment by caiosba** [comment]
Sure... actually you just need to send three: https://github.com/meedan/check-web/blob/develop/src/app/relay/CreateCommentMutation.js#L46

- `text`: String, the comment text itself
- `annotated_id`: String, the database `id` (`dbid`) of the media you created with the previous mutation
- `annotated_type`: String, in that case you can hard-code it to `ProjectMedia`
